spring:
  application:
    name: gbt-rmq
# RabbitMQ Config
  rabbitmq:
    host: 192.168.20.155
    port: 5672
    username: admin
    password: airag123
    publisher-confirms: true
    virtual-host: /
logging:
  level: debug